In [1]:
import torch
import torch.nn as nn

### 主要是了解 torch.autograd.grad()的用法

该函数的用法主要针对，想对输入的变量求导，而不是对参数求导时使用。

在WGAN-GP中，网络对输入变量进行了求导

该函数的主要参数为

inputs：求导的自变量

outputs：求导的应变量，对该输出求导

grad_outputs: 如果outputs是向量，则参数必须写，维度与outputs一致

retain_graph：True时保留计算图

create_Graphy: 若要计算高阶导数，则必须选为True

In [2]:
x = torch.rand(1,3,4,4)
x.requires_grad_()
print(x)

tensor([[[[0.0594, 0.1374, 0.2562, 0.0605],
          [0.2857, 0.9990, 0.7119, 0.2000],
          [0.2245, 0.6800, 0.1529, 0.4505],
          [0.2681, 0.0397, 0.0845, 0.8931]],

         [[0.8909, 0.6075, 0.9493, 0.4461],
          [0.8516, 0.5412, 0.6034, 0.7535],
          [0.8104, 0.4584, 0.9099, 0.4038],
          [0.8895, 0.6591, 0.0498, 0.7954]],

         [[0.3116, 0.4833, 0.3774, 0.4172],
          [0.1621, 0.0293, 0.1573, 0.5184],
          [0.4895, 0.7476, 0.2420, 0.4399],
          [0.9677, 0.7015, 0.9975, 0.2640]]]], requires_grad=True)


In [3]:
y = 4*x**2   # 对x求导 y = 8x
print(y)

tensor([[[[1.4112e-02, 7.5542e-02, 2.6263e-01, 1.4654e-02],
          [3.2649e-01, 3.9921e+00, 2.0274e+00, 1.5998e-01],
          [2.0155e-01, 1.8495e+00, 9.3559e-02, 8.1186e-01],
          [2.8756e-01, 6.3108e-03, 2.8579e-02, 3.1908e+00]],

         [[3.1749e+00, 1.4762e+00, 3.6045e+00, 7.9617e-01],
          [2.9007e+00, 1.1717e+00, 1.4562e+00, 2.2713e+00],
          [2.6273e+00, 8.4044e-01, 3.3119e+00, 6.5208e-01],
          [3.1645e+00, 1.7378e+00, 9.9356e-03, 2.5308e+00]],

         [[3.8844e-01, 9.3414e-01, 5.6980e-01, 6.9622e-01],
          [1.0510e-01, 3.4387e-03, 9.8998e-02, 1.0750e+00],
          [9.5842e-01, 2.2357e+00, 2.3428e-01, 7.7389e-01],
          [3.7460e+00, 1.9686e+00, 3.9804e+00, 2.7868e-01]]]],
       grad_fn=<MulBackward0>)


In [4]:
grad = torch.autograd.grad(inputs=x, outputs=y, grad_outputs=torch.ones_like(y),create_graph=True)[0]
print(grad)

tensor([[[[0.4752, 1.0994, 2.0499, 0.4842],
          [2.2856, 7.9921, 5.6954, 1.5999],
          [1.7958, 5.4399, 1.2235, 3.6041],
          [2.1450, 0.3178, 0.6762, 7.1452]],

         [[7.1273, 4.8600, 7.5942, 3.5691],
          [6.8126, 4.3299, 4.8269, 6.0283],
          [6.4836, 3.6670, 7.2794, 3.2301],
          [7.1156, 5.2730, 0.3987, 6.3634]],

         [[2.4930, 3.8660, 3.0194, 3.3376],
          [1.2968, 0.2346, 1.2586, 4.1473],
          [3.9160, 5.9809, 1.9361, 3.5188],
          [7.7419, 5.6123, 7.9804, 2.1116]]]], grad_fn=<MulBackward0>)


### 从上面看整个求导还是很直观的

In [6]:
print(grad.shape)

torch.Size([1, 3, 4, 4])


### 看一下pytorch中view的用法

In [31]:
batch = torch.rand((16,1,1,1))
print(batch.shape)

torch.Size([16, 1, 1, 1])


In [41]:
batch = batch.view(16,-1)
print(batch.shape[0])
print(batch)

16
tensor([[0.8858],
        [0.6395],
        [0.6865],
        [0.7583],
        [0.4189],
        [0.1305],
        [0.4896],
        [0.2876],
        [0.1015],
        [0.5248],
        [0.8505],
        [0.7853],
        [0.9922],
        [0.2488],
        [0.2364],
        [0.5840]])


In [29]:
a=torch.Tensor([[[1,2,3],[4,5,6]]])
print(a.shape)
print(a)

torch.Size([1, 2, 3])
tensor([[[1., 2., 3.],
         [4., 5., 6.]]])


In [30]:
a=a.view(1,-1)
print(a.shape)
print(a)

torch.Size([1, 6])
tensor([[1., 2., 3., 4., 5., 6.]])


### 下面是L2正则化的可视化


In [39]:
norm = torch.norm(input=batch,p=2,dim=0,keepdim=True)
print(norm)

tensor([[2.4133]])


In [40]:
p = torch.mean((norm - 1) ** 2)
print(p)

tensor(1.9973)
